---
title: "R Notebook"
output: html_notebook
---
Generalisiertes lineares Modell für das Land FRA erstellen
```{r}
glm.FRA_Inend<-glm(Arbeitstabelle_FRA_In$sqrt_InternetAnteil~Arbeitstabelle_FRA_In$ZeitNum)
plot( Arbeitstabelle_FRA_In$ZeitNum,Arbeitstabelle_FRA_In$sqrt_InternetAnteil)
abline(glm.FRA_Inend)
summary(glm.FRA_Inend)
segments(Arbeitstabelle_FRA_In$ZeitNum,fitted(glm.FRA_Inend), Arbeitstabelle_FRA_In$ZeitNum,Arbeitstabelle_FRA_In$sqrt_InternetAnteil)
```
Prognose mit manuellem Berechnen des Wertes für ZeitNum=18 (entspricht 2022)
```{r}
FRAsqrt_InternetAnteil_18<-7.15+0.17*18
new_row_sp18<-data.frame(ZeitNum=18, sqrt_InternetAnteil=FRAsqrt_InternetAnteil_18)
# Neue Zeilen in die Arbeitstabelle einbinden
Arbeitstabelle_FRA_In<-rbind(Arbeitstabelle_FRA_In, new_row_sp18)
```
Prognose mit manuellem Berechnen des Wertes für ZeitNum=19 (entspricht 2023)
```{r}
FRAsqrt_InternetAnteil_19<-7.15+0.17*19
new_row_sp19<-data.frame(ZeitNum=19, sqrt_InternetAnteil=FRAsqrt_InternetAnteil_19)
# Neue Zeilen in die Arbeitstabelle einbinden
Arbeitstabelle_FRA_In<-rbind(Arbeitstabelle_FRA_In, new_row_sp19)
```
Neue Variable "InternetAnteil" aus der wurzeltransformierten Variable "sqrt_InternetAnteil" berechnen
```{r}
Arbeitstabelle_FRA_In$InternetAnteil <- Arbeitstabelle_FRA_In$sqrt_InternetAnteil*Arbeitstabelle_FRA_In$sqrt_InternetAnteil
```